[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "easy"
version = "0.1.0"
description = "Email Analysis SYstem"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["easy"]
